name: PR & Issue Bot

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed, synchronize]

env:
  ISSUE_COMMENT: "感谢您的反馈！我们很快会查看并处理这个问题。"
  PR_OPENED_COMMENT: "感谢您提交的Pull Request！我们会尽快审查您的贡献。"
  PR_CLOSED_COMMENT: "感谢您的贡献！此Pull Request已关闭。"

jobs:
  issue-welcome:
    name: Welcome New Issue
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Comment on Issue
        uses: actions/github-script@7
        with:
          script: |
            const commentBody = process.env.ISSUE_COMMENT;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

  pr-welcome:
    name: Welcome New Pull Request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Comment on PR Opened
        uses: actions/github-script@latest
        with:
          script: |
            const commentBody = process.env.PR_OPENED_COMMENT;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

  pr-closed-feedback:
    name: Feedback on PR Closed
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Check PR Merge Status
        id: check_merge
        run: echo "::set-output name=merged::$([[ ${{ github.event.pull_request.merged }} == true ]] && echo 'true' || echo 'false')"
      - name: Comment on PR Closed
        if: steps.check_merge.outputs.merged == 'true'
        uses: actions/github-script@latest
        with:
          script: |
            const commentBody = process.env.PR_CLOSED_COMMENT;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
